Script started on 2015年03月10日 (週二) 22時24分46秒
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ ls
[0m[01;34mlab1[0m  lab1.script
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ hw[K[Khwoami.[K; pwd
No command 'hwoami' found, did you mean:
 Command 'whoami' from package 'coreutils' (main)
hwoami: command not found
/home/F74032162
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ whoami; pwd
F74032162
/home/F74032162
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ git confid[Kg o[Kil[K[K-l
user.name=andrewli
user.email=nyps70414@gmail.com
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ git cla[Kon [Ke https://hit[K[K[Kgithub.com/andrewli315/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ rm lab1
rm: cannot remove `lab1': Is a directory
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ ra[Kmdir lav[Kb1
rmdir: failed to remove `lab1': Directory not empty
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ cd lab1
]0;F74032162@2015cpp: ~/lab1F74032162@2015cpp:~/lab1$ ls
lab1.script
]0;F74032162@2015cpp: ~/lab1F74032162@2015cpp:~/lab1$ rm lab1.script
]0;F74032162@2015cpp: ~/lab1F74032162@2015cpp:~/lab1$ cd ..
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ ra[Kmdir lab1
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ ls
lab1.script
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ lsrmdir lab1[5Pcd ..rm lab1.scriptls[Kcd lab1[3@rmdir[C[C[C[C[C[3P lab1git clone https://github.com/andrewli315/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 4, done.[K
remote: Compressing objects:  25% (1/4)   [Kremote: Compressing objects:  50% (2/4)   [Kremote: Compressing objects:  75% (3/4)   [Kremote: Compressing objects: 100% (4/4)   [Kremote: Compressing objects: 100% (4/4), done.[K
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0[K
Unpacking objects:  25% (1/4)   Unpacking objects:  50% (2/4)   Unpacking objects:  75% (3/4)   Unpacking objects: 100% (4/4)   Unpacking objects: 100% (4/4), done.
]0;F74032162@2015cpp: ~F74032162@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 22時27分39秒
